Copy URL automatically to clipboard and get a confirmation on the paste page...
lmachens/copypasta pull request #15
Opened 2019-12-06 13:14 UTC by aruppert

...only if you pasted the text yourself.

![Screenshot 2019-12-06 at 14 13 46](https://user-images.githubusercontent.com/56864263/70325627-b9089400-1832-11ea-9cf4-436888b2b020.png)

2019-12-06 13:32 UTC, laurapauly reviewed
lgtm :)

2019-12-09 09:59 UTC, lmachens requested changes

2019-12-09 09:59 UTC, lmachens commented on client/src/components/Confirmation.js
> +export const flyFromRight = keyframes`
`Confirmation` is a copy of `Alert`. I would suggest to add a property to change the color.

2019-12-09 09:59 UTC, lmachens commented on client/src/App.js
> +          component={() => <Home isPasteCreator={isPasteCreator} />}
`isPasteCreator` is misleading because I would suggest having a boolean instead of a function

2019-12-09 09:59 UTC, lmachens commented on client/src/App.js
> +          component={() => <Home isPasteCreator={isPasteCreator} />}
`onPaste` maybe

2019-12-09 09:59 UTC, lmachens commented on client/src/pages/Paste.js
> +          <PasteArea onChange={copyURL()}>{paste.value}</PasteArea>
`copyURL` is executed on every render. Thus, `onChange` is undefined

2019-12-09 10:17 UTC, merged